name: C/C++ CI

on:
  push:
    branches: [ "stable" ]
  pull_request:
    branches: [ "stable" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: cd1
      run:  cd ./kernel
    - name: debug
      run: ls -la
    - name: get-deps
      run: ./get-deps
    - name: cd2
      run:  cd ../
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
