name: C/C++ CI

on:
  push:
    branches: [ "stable" ]
  pull_request:
    branches: [ "stable" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: get-deps
      run: ./kernel/get-deps-apt
    - name: make
      run: make
